# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
      docker:
        - image: circleci/node:10.14.0
      working_directory: ~/repo
      steps:
        - checkout
        - run: npm install
        - run: npm run build
        - store_artifacts:
            path: ~/repo/build
            destination: /tmp/build
  deploy:
      docker:
        - image: circleci/python:2.7-jessie
      working_directory: ~/repo
      steps:
        - run:
            name: Install awscli
            command: sudo pip install awscli
        - run:
            name: Deploy to S3
            command: aws s3 sync /tmp/build s3://mykolasavenko.com --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master